import { useEffect, useState } from "react";
import { DeleteOutlined, EditOutlined, ExperimentOutlined, PlusOutlined, ReloadOutlined } from "@ant-design/icons";
import { Button, DenseTable, Field, FormDrawer, PageHeader, Pagination, Select, StatusTag, useToast } from "./components";
import { useDemo } from "./store";
import { usePermissionRules } from "./permission-store";
import { departments, fieldOperators, grids, modules, newCondition, newConditionGroup, newPermissionRule, operations, operatorLabels, policyFields, policyUsers, requestObjects, responsibilityGroups, summarize, validateRule, valueLabel, workPolicyObject, type ConditionGroup, type ConditionNode, type ConditionResult, type Operator, type PermissionDecision, type PermissionRule, type PlanRequest } from "./permission-rules";
import type { Column } from "./types";

function Choices({ value, onChange, values, label, blank }: { value: string; onChange: (v: string) => void; values: string[]; label: string; blank?: string }) {
  return <Select value={value} onChange={onChange} ariaLabel={label}>{blank !== undefined && <option value="">{blank}</option>}{values.map((v) => <option key={v} value={v}>{valueLabel(v)}</option>)}</Select>;
}
function ConditionEditor({ node, onChange, onRemove, operation, depth = 0 }: { node: ConditionNode; onChange: (n: ConditionNode) => void; onRemove?: () => void; operation: string; depth?: number }) {
  if (node.type === "group") return <section className="permission-condition-group">
    <header><strong>{depth ? "條件組" : "校驗條件"}</strong><Choices label="條件符合方式" value={node.match} onChange={(match) => onChange({ ...node, match: match as "all" | "any" })} values={["all", "any"]} /><span className="permission-match-label">{node.match === "all" ? "全部符合" : "任一符合"}</span><div className="filter-spacer"/>{onRemove && <Button variant="text" icon={<DeleteOutlined/>} onClick={onRemove}>刪除組</Button>}</header>
    <div className="permission-condition-children">{node.children.map((child) => <ConditionEditor key={child.id} node={child} depth={depth + 1} operation={operation} onChange={(next) => onChange({ ...node, children: node.children.map((c) => c.id === child.id ? next : c) })} onRemove={() => onChange({ ...node, children: node.children.filter((c) => c.id !== child.id) })} />)}{!node.children.length && <div className="permission-hint">請加入至少一項條件；空條件組不能儲存。</div>}</div>
    <footer><Button icon={<PlusOutlined/>} onClick={() => onChange({ ...node, children: [...node.children, newCondition()] })}>新增條件</Button><Button disabled={depth >= 5} onClick={() => onChange({ ...node, children: [...node.children, newConditionGroup()] })}>新增條件組</Button></footer>
  </section>;
  const field = policyFields.find((f) => f.id === node.field)!;
  const available = policyFields.filter((f) => operation === "create-plan" ? f.source !== "對象" && !["relation.typeScope", "relation.executionMember", "relation.managementMember", "relation.inspectionMember"].includes(f.id) : f.source !== "請求" && !["relation.planning", "relation.requestGroupScope", "relation.requestObjectsScope"].includes(f.id));
  const references = policyFields.filter((f) => f.source === "對象" && f.kind === field.kind);
  const setField = (id: string) => { const next = policyFields.find((f) => f.id === id)!; onChange({ ...node, field: id, operator: fieldOperators(next.kind)[0], mode: "value", reference: undefined, value: next.kind === "boolean" ? "true" : next.kind === "number" ? "1" : next.options?.[0] ?? "" }); };
  const multiple = field.kind === "list" || node.operator === "in" || node.operator === "notIn";
  return <div className="permission-condition-row">
    <Field label="欄位"><Select value={node.field} onChange={setField} ariaLabel="條件欄位">{["用戶", "對象", "職責關係", "請求"].map((source) => <optgroup key={source} label={source}>{available.filter((f) => f.source === source).map((f) => <option key={f.id} value={f.id}>{f.label}</option>)}</optgroup>)}</Select></Field>
    <Field label="比較方式"><Select value={node.operator} onChange={(operator) => onChange({ ...node, operator: operator as Operator, value: field.kind === "text" && ["eq", "neq"].includes(operator) ? node.value.split("|")[0] : node.value })} ariaLabel="比較方式">{fieldOperators(field.kind).map((op) => <option key={op} value={op}>{operatorLabels[op]}</option>)}</Select></Field>
    {node.operator !== "unset" && <Field label="比較對象"><Select value={node.mode} onChange={(mode) => onChange({ ...node, mode: mode as "value" | "field", reference: references[0]?.id })} ariaLabel="比較對象"><option value="value">指定值</option>{references.length > 0 && operation !== "create-plan" && <option value="field">操作對象欄位</option>}</Select></Field>}
    {node.operator !== "unset" && <div className="field"><span>比較值</span>{node.mode === "field" ? <Select value={node.reference ?? ""} onChange={(reference) => onChange({ ...node, reference })} ariaLabel="比較欄位">{references.map((f) => <option key={f.id} value={f.id}>{f.label}</option>)}</Select> : field.kind === "number" ? <input aria-label="比較數字" type="number" value={node.value} onChange={(e) => onChange({ ...node, value: e.target.value })}/> : field.kind === "boolean" ? <Choices label="職責關係值" value={node.value} onChange={(value) => onChange({ ...node, value })} values={["true", "false"]}/> : multiple && field.options ? <div className="permission-multi-values" role="group" aria-label="比較值">{field.options.map((value) => <label key={value}><input type="checkbox" checked={node.value.split("|").includes(value)} onChange={(e) => onChange({ ...node, value: (e.target.checked ? [...node.value.split("|").filter(Boolean), value] : node.value.split("|").filter((v) => v !== value)).join("|") })}/>{valueLabel(value)}</label>)}</div> : field.options ? <Choices label="比較值" value={node.value} onChange={(value) => onChange({ ...node, value })} values={field.options}/> : <input aria-label="比較值" value={node.value} onChange={(e) => onChange({ ...node, value: e.target.value })}/>}</div>}
    <button className="permission-delete-condition" aria-label="刪除條件" onClick={onRemove}><DeleteOutlined/></button>
  </div>;
}

export function PlanRequestFields({ request, onChange }: { request: PlanRequest; onChange: (request: PlanRequest) => void }) {
  return <><Field label="附屬部門" required><Choices label="計劃附屬部門" value={request.department ?? ""} onChange={(department) => onChange({ ...request, department })} values={departments} blank="請選擇"/></Field><Field label="巡查群組" required><Select value={request.group ?? ""} onChange={(group) => onChange({ ...request, group })} ariaLabel="所選巡查群組"><option value="">請選擇</option>{responsibilityGroups.filter((g) => g.kind === "巡查").map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}</Select></Field><Field label="網格" required><Choices label="計劃網格" value={request.grid ?? ""} onChange={(grid) => onChange({ ...request, grid })} values={grids} blank="請選擇"/></Field><div className="field"><span><b>*</b>巡查對象</span><div className="permission-object-options" role="group" aria-label="巡查對象">{requestObjects.map((o) => <label key={o.id}><input type="checkbox" checked={request.objects?.includes(o.id) ?? false} onChange={(e) => onChange({ ...request, objects: e.target.checked ? [...(request.objects ?? []), o.id] : request.objects?.filter((id) => id !== o.id) })}/><span>{o.name}<small>{o.id} · {o.department} · {o.grid}</small></span></label>)}</div></div></>;
}
function ConditionTrace({ result }: { result: ConditionResult }) {
  return <li><div><StatusTag tone={result.result === "通過" ? "success" : result.result === "資料缺失" ? "danger" : "neutral"}>{result.result}</StatusTag><span>{result.summary}</span>{result.actual !== undefined && <small>實際值：{result.actual}</small>}</div>{result.children && <ul>{result.children.map((child) => <ConditionTrace key={child.id} result={child}/>)}</ul>}</li>;
}
export function DecisionView({ decision }: { decision: PermissionDecision }) {
  return <section className={`permission-decision ${decision.allowed ? "allowed" : "denied"}`} aria-live="polite">
    <header><h3>最終{decision.allowed ? "允許" : "拒絕"}</h3><StatusTag tone={decision.allowed ? "success" : "danger"}>{decision.allowed ? "允許" : "拒絕"}</StatusTag></header>
    <p>{decision.reason}</p><div className="permission-check-steps"><span>功能權限：{decision.functional ? "通過" : "拒絕"}</span><span>職責範圍：{decision.responsibility ? "通過" : "未通過／未執行"}</span><span>執行操作：不執行（試算）</span></div>
    {!!decision.forbiddenIdentities.length && <div className="permission-hint">命中禁止身份：{decision.forbiddenIdentities.join("、")}</div>}
    {!decision.rules.length && <div className="permission-hint">沒有執行適用的生效規則，或校驗已在功能權限／資料檢查階段終止。</div>}
    {decision.rules.map((rule) => <details key={rule.id} open>
      <summary><strong>{rule.code} · {rule.name} · v{rule.version}</strong><StatusTag tone={rule.matched ? rule.effect === "拒絕" ? "danger" : "success" : "neutral"}>{rule.effect}規則 · {rule.matched ? "命中" : "未命中"}</StatusTag></summary>
      {rule.error && <p className="permission-error">{rule.error}</p>}
      {rule.attempts ? rule.attempts.map((attempt) => <details key={attempt.group} open={attempt.group === rule.witness}>
        <summary><strong>{attempt.group}</strong><span>條件：{attempt.conditions.result}</span>{rule.effect === "允許" && <span>完整職責範圍：{attempt.responsibility ? "通過" : "不符合"}</span>}</summary>
        <ul className="permission-trace"><ConditionTrace result={attempt.conditions}/></ul>
      </details>) : <ul className="permission-trace"><ConditionTrace result={rule.conditions}/></ul>}
    </details>)}
  </section>;
}
function RuleSimulation({ rule }: { rule: PermissionRule }) {
  const { works } = useDemo(); const { check } = usePermissionRules();
  const [userId, setUserId] = useState(policyUsers[2].id); const [operation, setOperation] = useState(rule.operation);
  const [objectId, setObjectId] = useState(works.find((w) => w.status === "已解決")?.id ?? works[0]?.id ?? "");
  const [request, setRequest] = useState<PlanRequest>({ group: "inspect-middle", department: "環境衛生部", grid: "大堂南區", objects: ["OBJ-002"] });
  const [decision, setDecision] = useState<PermissionDecision | null>(null);
  useEffect(() => { setDecision(null); }, [userId, operation, objectId, request, rule]);
  const user = policyUsers.find((u) => u.id === userId)!;
  const run = (current: boolean) => {
    const work = works.find((w) => w.id === objectId);
    const object = operation === "execute-inspection" ? { id: "INSP-DEMO-001", department: "設施管理部", type: "公共設施／座椅", grid: "花地瑪堂北區", status: "進行中", inspectionGroup: "inspect-north" } : work ? workPolicyObject(work) : undefined;
    setDecision(check({ user, operation, object: operation === "create-plan" ? undefined : object, request: operation === "create-plan" ? request : undefined, groups: responsibilityGroups }, current ? rule : undefined));
  };
  return <div className="permission-simulation"><div className="permission-hint">使用示範權責資料；試算不會執行業務操作。提交時另以目前登入用戶重新校驗。管理員亦不跳過校驗。</div><section className="group-editor-section"><header><h3>試算輸入</h3></header><div className="group-editor-grid"><Field label="操作用戶"><Select value={userId} onChange={setUserId} ariaLabel="試算用戶">{policyUsers.map((u) => <option key={u.id} value={u.id}>{u.name}（{u.account}）</option>)}</Select></Field><Field label="操作"><Select value={operation} onChange={setOperation} ariaLabel="試算操作">{operations.map((op) => <option key={op.id} value={op.id}>{op.module}／{op.name}</option>)}</Select></Field>{operation === "create-plan" ? <PlanRequestFields request={request} onChange={setRequest}/> : operation === "execute-inspection" ? <Field label="巡查記錄"><input readOnly value="INSP-DEMO-001 · 北區公園設施巡查（示範）"/></Field> : <Field label="操作對象"><Select value={objectId} onChange={setObjectId} ariaLabel="試算工作"><option value="">未選擇（資料缺失）</option>{works.map((w) => <option key={w.id} value={w.id}>{w.id} · {w.title}（{w.status}）</option>)}</Select></Field>}</div><div className="permission-user-context"><strong>{user.name}的群組身份</strong>{user.groups.map((id) => { const g = responsibilityGroups.find((item) => item.id === id)!; return <div key={id}>{g.name}（{g.kind}）<small>部門：{g.department} · 工作類型：{g.types.join("、")} · 網格：{g.grids.join("、")}</small></div>; })}</div></section><div className="permission-simulation-actions"><Button icon={<ExperimentOutlined/>} disabled={operation !== rule.operation} onClick={() => run(true)}>只試算目前規則</Button><Button variant="primary" icon={<ExperimentOutlined/>} onClick={() => run(false)}>試算全部生效規則</Button></div><div className="permission-hint">目前規則試算包含未儲存條件，但失效規則不參與判定；單項允許結果不代表能覆蓋其他拒絕規則。</div>{decision && <DecisionView decision={decision}/>}</div>;
}

export function PermissionRulesPage() {
  const { rules, saveRule, logs, storageError } = usePermissionRules(); const { showToast } = useToast();
  const emptyFilters = { code: "", name: "", module: "", operation: "", effect: "", status: "" };
  const [filters, setFilters] = useState(emptyFilters); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(15);
  const [draft, setDraft] = useState<PermissionRule | null>(null); const [tab, setTab] = useState("基礎數據"); const [error, setError] = useState(""); const [showLogs, setShowLogs] = useState(false);
  const filter = (key: keyof typeof emptyFilters, value: string) => { setFilters((f) => ({ ...f, [key]: value, ...(key === "module" ? { operation: "" } : {}) })); setPage(1); };
  const rows = rules.filter((r) => r.code.toLowerCase().includes(filters.code.toLowerCase()) && r.name.includes(filters.name) && (!filters.module || r.module === filters.module) && (!filters.operation || r.operation === filters.operation) && (!filters.effect || r.effect === filters.effect) && (!filters.status || r.status === filters.status));
  const open = (rule: PermissionRule, targetTab = "基礎數據") => { setDraft(structuredClone(rule)); setTab(targetTab); setError(""); };
  const change = (patch: Partial<PermissionRule>) => { setDraft((d) => d ? { ...d, ...patch } : null); setError(""); };
  const save = () => { if (!draft) return; const errors = validateRule(draft, rules); const message = errors.length ? errors.join(" ") : saveRule(draft); if (message) { setError(message); return; } setDraft(null); showToast("校驗規則已儲存，下次提交使用最新規則。"); };
  const columns: Column<PermissionRule>[] = ([
    { key: "code", title: "編號", width: 150 }, { key: "name", title: "名稱", width: 230 }, { key: "module", title: "業務模組", width: 130 },
    { key: "operation", title: "操作", width: 160, render: (r) => operations.find((op) => op.id === r.operation)?.name, sortValue: (r) => operations.find((op) => op.id === r.operation)?.name ?? "" },
    { key: "effect", title: "規則效果", width: 100, render: (r) => <StatusTag tone={r.effect === "拒絕" ? "danger" : "success"}>{r.effect}</StatusTag> },
    { key: "conditions", title: "條件摘要", width: 430, render: (r) => <span className="permission-summary-cell">{summarize(r.conditions)}</span>, sortValue: (r) => summarize(r.conditions) },
    { key: "status", title: "狀態", width: 95, render: (r) => <StatusTag tone={r.status === "生效" ? "success" : "neutral"}>{r.status}</StatusTag> },
    { key: "updatedBy", title: "更新人", width: 100 }, { key: "updatedAt", title: "更新時間", width: 180 },
  ] satisfies Column<PermissionRule>[]).map((col) => ({ ...col, sortable: true }));
  return <div className="page-content permission-rules-page"><PageHeader title="權限校驗規則" actions={<><Button onClick={() => setShowLogs(true)}>校驗紀錄</Button><Button variant="primary" icon={<PlusOutlined/>} onClick={() => open(newPermissionRule())}>新增規則</Button></>}/>{storageError && <div className="permission-error" role="alert">{storageError}</div>}<section className="panel list-panel permission-list-panel"><div className="filter-bar permission-filters"><Field label="編號"><input value={filters.code} onChange={(e) => filter("code", e.target.value)} placeholder="規則編號"/></Field><Field label="名稱"><input value={filters.name} onChange={(e) => filter("name", e.target.value)} placeholder="規則名稱"/></Field><Field label="業務模組"><Choices label="篩選業務模組" value={filters.module} onChange={(v) => filter("module", v)} values={modules} blank="全部模組"/></Field><Field label="操作"><Select value={filters.operation} onChange={(v) => filter("operation", v)} ariaLabel="篩選操作"><option value="">全部操作</option>{operations.filter((op) => !filters.module || op.module === filters.module).map((op) => <option key={op.id} value={op.id}>{op.name}</option>)}</Select></Field><Field label="規則效果"><Choices label="篩選效果" value={filters.effect} onChange={(v) => filter("effect", v)} values={["允許", "拒絕"]} blank="全部效果"/></Field><Field label="狀態"><Choices label="篩選狀態" value={filters.status} onChange={(v) => filter("status", v)} values={["生效", "失效"]} blank="全部狀態"/></Field><Button variant="text" icon={<ReloadOutlined/>} onClick={() => { setFilters(emptyFilters); setPage(1); }}>重設</Button></div><DenseTable rows={rows} columns={columns} stickyActions actionTitle="操作" page={Math.min(page, Math.max(1, Math.ceil(rows.length / pageSize)))} pageSize={pageSize} onSort={() => setPage(1)} renderActions={(r) => <div className="permission-row-actions"><Button variant="text" className="table-action-button" icon={<EditOutlined/>} onClick={() => open(r)}>編輯</Button></div>}/><Pagination total={rows.length} page={page} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1); }}/></section>
    <FormDrawer open={!!draft} title={draft?.updatedAt ? "編輯校驗規則" : "新增校驗規則"} className="permission-editor-drawer" onClose={() => setDraft(null)} onSubmit={save}>{draft && <div className="permission-editor-form"><nav className="bip-editor-tabs" role="tablist" aria-label="校驗規則">{["基礎數據", "校驗條件", "規則試算"].map((t) => <button role="tab" aria-selected={tab === t} aria-controls={`permission-tab-${t}`} id={`permission-nav-${t}`} key={t} className={tab === t ? "active" : ""} onClick={() => setTab(t)}>{t}</button>)}</nav>{error && <div className="permission-error" role="alert">{error}</div>}<div className="permission-tab-content" role="tabpanel" id={`permission-tab-${tab}`} aria-labelledby={`permission-nav-${tab}`}>
      {tab === "基礎數據" && <><section className="group-editor-section"><header><h3>基礎數據</h3></header><div className="group-editor-grid"><Field label="編號" required><input value={draft.code} onChange={(e) => change({ code: e.target.value })} placeholder="唯一規則編號"/></Field><Field label="名稱" required><input value={draft.name} onChange={(e) => change({ name: e.target.value })}/></Field><Field label="業務模組" required><Choices label="規則業務模組" value={draft.module} onChange={(module) => change({ module, operation: operations.find((op) => op.module === module)!.id, conditions: newConditionGroup() })} values={modules}/></Field><Field label="操作" required><Select value={draft.operation} onChange={(operation) => change({ operation, conditions: newConditionGroup() })} ariaLabel="規則操作">{operations.filter((op) => op.module === draft.module).map((op) => <option key={op.id} value={op.id}>{op.name}</option>)}</Select></Field><Field label="操作對象"><input value={operations.find((op) => op.id === draft.operation)?.object ?? ""} readOnly/></Field><Field label="規則效果" required><Choices label="規則效果" value={draft.effect} onChange={(effect) => change({ effect: effect as PermissionRule["effect"] })} values={["允許", "拒絕"]}/></Field>{draft.effect === "拒絕" && <Field label="拒絕提示語" required><textarea value={draft.message} onChange={(e) => change({ message: e.target.value })} rows={3} placeholder="向操作用戶顯示具體拒絕原因"/></Field>}<Field label="規則說明"><textarea value={draft.description} onChange={(e) => change({ description: e.target.value })} rows={3}/></Field></div></section><section className="group-editor-section"><header><h3>校驗規則狀態</h3></header><div className="group-editor-status"><div className="bip-field"><span>狀態</span><div className="switch-row"><label className="switch-control"><input type="checkbox" aria-label="規則生效" checked={draft.status === "生效"} onChange={(e) => change({ status: e.target.checked ? "生效" : "失效" })}/><span className="switch"/></label></div></div><div className="group-editor-count"><span>目前規則版本</span><strong>v{draft.version}</strong></div></div></section></>}
      {tab === "校驗條件" && <><div className="permission-hint">「全部符合／任一符合」可巢狀分組。所有職責關係必須由同一個用戶群組滿足，不能拼接不同群組的授權。更改模組或操作會重設條件。</div><ConditionEditor node={draft.conditions} operation={draft.operation} onChange={(conditions) => change({ conditions: conditions as ConditionGroup })}/><section className="permission-rule-summary"><h3>自動規則摘要</h3><p>{summarize(draft.conditions)}</p></section></>}
      {tab === "規則試算" && <RuleSimulation rule={draft}/>}</div></div>}</FormDrawer>
    <FormDrawer open={showLogs} title="權限校驗紀錄" className="permission-editor-drawer" onClose={() => setShowLogs(false)}><div className="permission-hint">保留最近 500 筆本地示範紀錄；正式環境須由服務端保存不可竄改的審計紀錄。</div>{!logs.length && <div className="empty-state">暫無校驗紀錄</div>}{logs.map((log) => <details className="permission-log" key={log.id}><summary><StatusTag tone={log.decision.allowed ? "success" : "danger"}>{log.decision.allowed ? "允許" : "拒絕"}</StatusTag><strong>{log.user} · {operations.find((op) => op.id === log.operation)?.name ?? log.operation}</strong><span>{log.time} · {log.mode}</span></summary><dl className="detail-list"><div><dt>用戶編號</dt><dd>{log.userId}</dd></div><div><dt>操作對象</dt><dd>{log.objectId}</dd></div><div><dt>規則版本</dt><dd>{log.versions.join("、") || "未執行規則"}</dd></div><div><dt>原因</dt><dd>{log.decision.reason}</dd></div></dl></details>)}</FormDrawer>
  </div>;
}
